# load libraries ---------------------------

library("tidyverse")
library("papaja")
library("knitr")
library("here")
library("fs")
library("purrr")
library("dplyr")
library("tidyr")
library("forcats")
library("readr")
library("readxl")
library("writexl")
library("glue")
library("ggplot2")
#library("ganttrify")
#library("contributoR")
library("magick")
library("webshot")
library("kableExtra")
library("hrbrthemes")
library("gridExtra")
library("sjPlot")
library("sjlabelled")
library("sjmisc")
library("lme4")
library("lmerTest")
library("brms")
library("emmeans")
library("tidyr")
library("dplyr")
library("stringr")
library("glue")
library("purrr")
library("forcats")
library("fs")
library("ggplot2")
library("bayesplot")
library("tidybayes")
library("ggbeeswarm")
library("patchwork")
library("ggdag")
library("readr")
library("here")
library("broom")
library("brms")
library("future")
library("bayestestR")
library("stringr")
library("flextable")
#library("cmdstanr")

round2 <- function(x) sprintf("%.2f", x)

# ------------------------------------------